/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author iago-
 */
public class Crud extends javax.swing.JFrame {

    /**
     * Creates new form Crud
     */
    public Crud() {
        initComponents();
        
        
        jScrollPane1.getViewport().setBackground(Color.white);
        
        Funcoes.setListar("");
        
        jPopupMenu1.add(menu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btnEditar = new java.awt.Button();
        btnExcluir = new java.awt.Button();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnNovo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnEncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bntEliminarTodos = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        menu.setBackground(new java.awt.Color(0, 126, 51));

        btnEditar.setBackground(new java.awt.Color(0, 126, 51));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setLabel("Alterar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(0, 126, 51));
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setLabel("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnNovo1.setBackground(new java.awt.Color(0, 126, 51));
        btnNovo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovo1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo1.setText("Novo");
        btnNovo1.setToolTipText("Registrar Usuário");
        btnNovo1.setName("btnNovo"); // NOI18N
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 126, 51));

        btnEncerrar.setBackground(new java.awt.Color(0, 126, 51));
        btnEncerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEncerrar.setText("X");
        btnEncerrar.setToolTipText("Encerrar");
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("JAVA & MYSQL- REGISTRAR, EDITAR E APAGAR ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncerrar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEncerrar)
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabela.setBackground(new java.awt.Color(0, 153, 51));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "USUARIO", "SENHA", "SEXO", "ENDEREÇO", "BAIRRO", "CIDADE", "CEP", "E-MAIL", "UF", "IDIOMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setComponentPopupMenu(jPopupMenu1);
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);

        btnNovo.setBackground(new java.awt.Color(0, 126, 51));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Registrar Usuário");
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("* Para Editar ou Remover clique na linha desejada e depois clique com o botão direito do mouse.");

        bntEliminarTodos.setBackground(new java.awt.Color(0, 126, 51));
        bntEliminarTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntEliminarTodos.setForeground(new java.awt.Color(255, 255, 255));
        bntEliminarTodos.setText("Excluir Todos");
        bntEliminarTodos.setToolTipText("Registrar Usuário");
        bntEliminarTodos.setName("btnNovo"); // NOI18N
        bntEliminarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEliminarTodosActionPerformed(evt);
            }
        });

        txtBuscar.setText("Buscar...");
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntEliminarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(bntEliminarTodos)
                    .addComponent(txtBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnEncerrarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
     Formulario_Registro f = new Formulario_Registro(this, true);
     f.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tabela.getSelectedRow();
        
        Formulario_Update f = new Formulario_Update(this, true);
        f.txtNome.setText(tabela.getValueAt(fila, 1).toString());
        f.txtUsuario.setText(tabela.getValueAt(fila, 2).toString());
        f.txtPassword.setText(tabela.getValueAt(fila, 3).toString());
        if(tabela.getValueAt(fila, 4).toString() == "M"){
            f.rbtMasculino.setSelected(true);
        } else {
            f.rbtFeminino.setSelected(true);
        }
        f.txtEndereco.setText(tabela.getValueAt(fila, 5).toString());
        f.txtBairro.setText(tabela.getValueAt(fila, 6).toString());
        f.txtCidade.setText(tabela.getValueAt(fila, 7).toString());
        f.txtCep.setText(tabela.getValueAt(fila, 8).toString());
        f.txtEmail.setText(tabela.getValueAt(fila, 9).toString());
        if(tabela.getValueAt(fila, 10).toString() == "MA"){
            f.cboUf.setSelectedIndex(0);
        } else if(tabela.getValueAt(fila, 10).toString() == "PI"){
            f.cboUf.setSelectedIndex(1);
        } else if(tabela.getValueAt(fila, 10).toString() == "PA"){
            f.cboUf.setSelectedIndex(2);
        } else if(tabela.getValueAt(fila, 10).toString() == "TO"){
            f.cboUf.setSelectedIndex(3);
        }
        //0 - inglês;\n1 - espanhol;\n2 - francês;\n3 - inglês e espanhol;\n
        //4 - inglês e francês;\n5 - espanhol e fracês.\n6 - inglês, espanhol e francês.
        if(tabela.getValueAt(fila, 11).toString() == "Inglês"){
            f.jcbIngles.setSelected(true);
        } else if (tabela.getValueAt(fila, 11).toString() == "Espanhol"){
            f.jcbEspanhol.setSelected(true);
        }else if (tabela.getValueAt(fila, 11).toString() == "Francês"){
            f.jcbFrances.setSelected(true);
        }else if (tabela.getValueAt(fila, 11).toString() == "Inglês e Espanhol"){
            f.jcbIngles.setSelected(true);
            f.jcbEspanhol.setSelected(true);
        }else if (tabela.getValueAt(fila, 11).toString() == "Inglês e Francês"){
            f.jcbIngles.setSelected(true);
            f.jcbFrances.setSelected(true);
        }else if (tabela.getValueAt(fila, 11).toString() == "Espanhol e Francês"){
            f.jcbEspanhol.setSelected(true);
            f.jcbFrances.setSelected(true);
        }else if (tabela.getValueAt(fila, 11).toString() == "Inglês, Espanhol e Francês"){
            f.jcbIngles.setSelected(true);
            f.jcbEspanhol.setSelected(true);
            f.jcbFrances.setSelected(true);
        }
    
        f.lblId.setText(tabela.getValueAt(fila, 0).toString());
        
        f.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int fila = tabela.getSelectedRow();
        
        Sentencias s = new Sentencias();
        s.setId(Integer.parseInt(tabela.getValueAt(fila, 0).toString()));
        
        if(JOptionPane.showConfirmDialog(this, "Deseja Excluir Registro", "", 
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            if(Funcoes.isDelete(s)){
                Funcoes.setListar("");
                JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Excluir registro", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void bntEliminarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarTodosActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Deseja Excluir TODOS os Registros", "", 
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            if(Funcoes.isTruncate()){
                Funcoes.setListar("");
                JOptionPane.showMessageDialog(this, "TODOS os Usuários excluído com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Excluir os registros", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bntEliminarTodosActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        Funcoes.setListar(this.txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEliminarTodos;
    private java.awt.Button btnEditar;
    private javax.swing.JButton btnEncerrar;
    private java.awt.Button btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    public static javax.swing.JTable tabela;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
